apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
    name: my-traefik-themepark
    namespace: default
spec:
    plugin:
        traefik-themepark:
            app: sonarr
            theme: dark
