apiVersion: traefik.containo.us/v1alpha1
kind: Service
apiVersion: v1
metadata:
  name: jellyfin
spec:
  externalIPs:
    - 10.10.0.70 
  ports:
  - protocol: TCP
    port: 8096
    targetPort: 8096
    name: http
---
kind: Endpoints
apiVersion: v1
metadata:
  name: jellyfin
subsets:
  - addresses:
    - ip: 10.10.0.70
    ports:
    - protocol: TCP
      port: 8096
      name: http
--- 
 apiVersion: traefik.containo.us/v1alpha1 
 kind: IngressRoute 
 metadata: 
   name: jellyfin-lan
   annotations:  
     kubernetes.io/ingress.class: traefik-external 
 spec: 
   entryPoints: 
     - websecure 
   routes: 
     - match: Host(`jelly.k3s.resulaj.eu`) 
       kind: Rule 
       services: 
         - name: jellyfin 
           port: 8096 
       middlewares: 
         - name: default-headers 
   tls: 
     secretName: k3s-resulaj-eu-production-tls


# External-Network
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin-wan
  namespace: default
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jelly.resulaj.eu`)
      kind: Rule
      services:
        - name: jellyfin
          port: 8096
      middlewares:
        - name: default-headers
  tls:
    secretName: resulaj-eu-production-tls