apiVersion: traefik.containo.us/v1alpha1
kind: Service
apiVersion: v1
metadata:
  name: nexus
spec:
  externalIPs:
    - 10.10.0.2  
  ports:
  - protocol: TCP
    port: 8006
    targetPort: 8006
    name: https
---
kind: Endpoints
apiVersion: v1
metadata:
  name: nexus
subsets:
  - addresses:
    - ip: 10.10.0.2
    ports:
    - protocol: TCP
      port: 8006
      name: https
--- 
 apiVersion: traefik.containo.us/v1alpha1 
 kind: IngressRoute 
 metadata: 
   name: nexus 
   annotations:  
     kubernetes.io/ingress.class: traefik-external 
 spec: 
   entryPoints: 
     - websecure 
   routes: 
     - match: Host(`nexus.k3s.resulaj.eu`) 
       kind: Rule 
       services: 
         - name: nexus 
           port: 8006 
       middlewares: 
         - name: default-headers 
   tls: 
     secretName: k3s-resulaj-eu-production-tls